// <auto-generated />
using System;
using Inventor.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inventor.Api.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260621172338_AddVendorFinance")]
    partial class AddVendorFinance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Inventor.Api.Models.Entities.InventoryLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProcessExecutionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalCost")
                        .HasColumnType("double precision");

                    b.Property<string>("UOM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("UnitCost")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ProcessExecutionId");

                    b.HasIndex("ProductId");

                    b.ToTable("InventoryLedgers");
                });

            modelBuilder.Entity("Inventor.Api.Models.Entities.ProcessCostDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CostType")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProcessDefinitionVersionId")
                        .HasColumnType("uuid");

                    b.Property<double>("Rate")
                        .HasColumnType("double precision");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UOM")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProcessDefinitionVersionId");

                    b.ToTable("ProcessCostDefinitions");
                });

            modelBuilder.Entity("Inventor.Api.Models.Entities.ProcessDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProcessDefinitions");
                });

            modelBuilder.Entity("Inventor.Api.Models.Entities.ProcessDefinitionVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("ProcessDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcessDefinitionId");

                    b.ToTable("ProcessDefinitionVersions");
                });

            modelBuilder.Entity("Inventor.Api.Models.Entities.ProcessExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ActualOutputQty")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PlannedQty")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProcessDefinitionVersionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ScrapQty")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalCost")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProcessDefinitionVersionId");

                    b.HasIndex("VendorId");

                    b.ToTable("ProcessExecutions");
                });

            modelBuilder.Entity("Inventor.Api.Models.Entities.ProcessExecutionCost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CostType")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProcessExecutionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<double>("Rate")
                        .HasColumnType("double precision");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalCost")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ProcessExecutionId");

                    b.ToTable("ProcessExecutionCosts");
                });

            modelBuilder.Entity("Inventor.Api.Models.Entities.ProcessExecutionIO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("ActualCost")
                        .HasColumnType("double precision");

                    b.Property<decimal>("ActualQty")
                        .HasColumnType("numeric");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<decimal>("PlannedQty")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProcessExecutionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("UnitCost")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ProcessExecutionId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProcessExecutionIOs");
                });

            modelBuilder.Entity("Inventor.Api.Models.Entities.ProcessIODefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProcessDefinitionVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ScrapPercentage")
                        .HasColumnType("numeric");

                    b.Property<decimal>("StandardQty")
                        .HasColumnType("numeric");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UOM")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProcessDefinitionVersionId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProcessIODefinitions");
                });

            modelBuilder.Entity("Inventor.Api.Models.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CurrentQuantity")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductType")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UOM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Inventor.Api.Models.Entities.ProductCost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<int>("CostType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UOM")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductCosts");
                });

            modelBuilder.Entity("Inventor.Api.Models.Entities.ProductPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PriceType")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductPrices");
                });

            modelBuilder.Entity("Inventor.Api.Models.Entities.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VendorType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("Inventor.Api.Models.Entities.VendorTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.ToTable("VendorTransactions");
                });

            modelBuilder.Entity("Inventor.Api.Models.Entities.InventoryLedger", b =>
                {
                    b.HasOne("Inventor.Api.Models.Entities.ProcessExecution", "ProcessExecution")
                        .WithMany()
                        .HasForeignKey("ProcessExecutionId");

                    b.HasOne("Inventor.Api.Models.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessExecution");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Inventor.Api.Models.Entities.ProcessCostDefinition", b =>
                {
                    b.HasOne("Inventor.Api.Models.Entities.ProcessDefinitionVersion", "ProcessDefinitionVersion")
                        .WithMany("Costs")
                        .HasForeignKey("ProcessDefinitionVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessDefinitionVersion");
                });

            modelBuilder.Entity("Inventor.Api.Models.Entities.ProcessDefinitionVersion", b =>
                {
                    b.HasOne("Inventor.Api.Models.Entities.ProcessDefinition", "ProcessDefinition")
                        .WithMany("Versions")
                        .HasForeignKey("ProcessDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessDefinition");
                });

            modelBuilder.Entity("Inventor.Api.Models.Entities.ProcessExecution", b =>
                {
                    b.HasOne("Inventor.Api.Models.Entities.ProcessDefinitionVersion", "ProcessDefinitionVersion")
                        .WithMany()
                        .HasForeignKey("ProcessDefinitionVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventor.Api.Models.Entities.Vendor", "Vendor")
                        .WithMany("ProcessExecutions")
                        .HasForeignKey("VendorId");

                    b.Navigation("ProcessDefinitionVersion");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Inventor.Api.Models.Entities.ProcessExecutionCost", b =>
                {
                    b.HasOne("Inventor.Api.Models.Entities.ProcessExecution", "ProcessExecution")
                        .WithMany("Costs")
                        .HasForeignKey("ProcessExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessExecution");
                });

            modelBuilder.Entity("Inventor.Api.Models.Entities.ProcessExecutionIO", b =>
                {
                    b.HasOne("Inventor.Api.Models.Entities.ProcessExecution", "ProcessExecution")
                        .WithMany("IOs")
                        .HasForeignKey("ProcessExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventor.Api.Models.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessExecution");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Inventor.Api.Models.Entities.ProcessIODefinition", b =>
                {
                    b.HasOne("Inventor.Api.Models.Entities.ProcessDefinitionVersion", "ProcessDefinitionVersion")
                        .WithMany("IOs")
                        .HasForeignKey("ProcessDefinitionVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventor.Api.Models.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessDefinitionVersion");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Inventor.Api.Models.Entities.ProductCost", b =>
                {
                    b.HasOne("Inventor.Api.Models.Entities.Product", "Product")
                        .WithMany("Costs")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Inventor.Api.Models.Entities.ProductPrice", b =>
                {
                    b.HasOne("Inventor.Api.Models.Entities.Product", "Product")
                        .WithMany("Prices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Inventor.Api.Models.Entities.VendorTransaction", b =>
                {
                    b.HasOne("Inventor.Api.Models.Entities.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Inventor.Api.Models.Entities.ProcessDefinition", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Inventor.Api.Models.Entities.ProcessDefinitionVersion", b =>
                {
                    b.Navigation("Costs");

                    b.Navigation("IOs");
                });

            modelBuilder.Entity("Inventor.Api.Models.Entities.ProcessExecution", b =>
                {
                    b.Navigation("Costs");

                    b.Navigation("IOs");
                });

            modelBuilder.Entity("Inventor.Api.Models.Entities.Product", b =>
                {
                    b.Navigation("Costs");

                    b.Navigation("Prices");
                });

            modelBuilder.Entity("Inventor.Api.Models.Entities.Vendor", b =>
                {
                    b.Navigation("ProcessExecutions");
                });
#pragma warning restore 612, 618
        }
    }
}
